SSL/TLS-Modules
arkid15r/owasp-nettacker pull request #1
Opened 2024-06-08 07:03 UTC by Captain-T2004

Added the SSL/TLS modules to scan for ssl certificate vulnerabilities and to scan for old ssl/tls version or bad cipher suite.

#### Checklist
- [x] I have followed the [Contributor Guidelines](https://github.com/OWASP/Nettacker/wiki/Developers#contribution-guidelines).
- [x] The code has been thoroughly tested in my local development environment with flake8 and pylint.
- [x] The code is Python 3 compatible.
- [ ] The code follows the PEP8 styling guidelines with 4 spaces indentation.
- [x] This Pull Request relates to only one issue or only one feature
- [ ] I have referenced the corresponding issue number in my commit message
- [ ] I have added the relevant documentation.
- [ ] My branch is up-to-date with the Upstream master branch.

#### Changes proposed in this pull request

#### Your development environment
- OS: `Kali GNU/Linux `
- OS Version: `Rolling x`
- Python Version: `Python 3.11.9`

2024-06-13 18:38 UTC, arkid15r reviewed
I've updated the code w/ some refactoring/reformatting.

2024-06-26 00:45 UTC, arkid15r requested changes
Looks great, please take a look into addressing the comments when you get a chance:

2024-06-26 00:45 UTC, arkid15r commented on src/nettacker/core/module.py
> +            "ssl_version_scan",
Do we really have to extend this list w/ ssl_ modules?

2024-06-26 00:45 UTC, arkid15r commented on tests/core/test_utils.py
> +            self.assertEqual(utils.is_weak_hash_algo(algo), True)
Here and and everywhere else
```suggestion
            self.assertTrue(utils.is_weak_hash_algo(algo))
```

2024-06-26 00:45 UTC, arkid15r commented on tests/core/test_utils.py
> +        self.assertEqual(utils.is_weak_hash_algo("test_aglo"), False)
```suggestion
        self.assertFalse(utils.is_weak_hash_algo("test_aglo"))
```

2024-06-26 00:45 UTC, arkid15r commented on tests/core/test_socket.py
> +class TestSSLMethods(TestCase):
Could you group/split the test cases by good/bad cert input?

2024-06-26 00:45 UTC, arkid15r commented on src/nettacker/core/utils/common.py
> +        except Exception:
Is it possible to narrow down the expected Exception to minimize false negatives?

2024-06-26 00:45 UTC, arkid15r commented on src/nettacker/core/utils/common.py
> +def check_cipher_suite(host, port, timeout):
Would it be more consistent if you used `is_weak_ssl_version` and `is_weak_cipher_suite` names?

2024-06-26 00:45 UTC, arkid15r commented on tests/core/test_utils.py
> +    def test_check_cipher_suite(self, mock_wrap, mock_socket):
It seems we lack tests based on the cipher value here

2024-06-26 00:48 UTC, arkid15r commented
@securestep9 I'm unable to add you as a reviewer here. Could you review when you get a chance?

2024-06-26 10:00 UTC, Captain-T2004 commented on src/nettacker/core/module.py
> +            "ssl_version_scan",
I have tried to run it without populating this list and it return: "KeyError: 'socket'", this happens with all the modules using socket library. I can look into it more but without any changes somewhere in the code the modules won't work without populating this list.

2024-06-27 15:02 UTC, Captain-T2004 commented
@arkid15r, I have made the requested changes please review it again. Also on your last comment, I can't think of how to add cipher value based test as per the current login if the ssl connection is established using the provided unsecure_cipher than the method returns True else it returns False. So how can I write a test based on the cipher value?

2024-07-04 00:30 UTC, arkid15r approved these changes
No worries, I misread the function code. The tests are fine.

LGTM

2024-07-04 00:32 UTC, merged